// <auto-generated />
using System;
using Mahjong.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mahjong.Api.Migrations
{
    [DbContext(typeof(MahjongDbContext))]
    [Migration("20260726162559_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Mahjong.Api.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoundWind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinningPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayGroupId");

                    b.HasIndex("WinnerPlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Mahjong.Api.Models.GameParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDealer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatWind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("GameId", "SeatWind")
                        .IsUnique();

                    b.ToTable("GameParticipations");
                });

            modelBuilder.Entity("Mahjong.Api.Models.PlayGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlayGroups");
                });

            modelBuilder.Entity("Mahjong.Api.Models.PlayGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayGroupId", "PlayerId")
                        .IsUnique();

                    b.ToTable("PlayGroupMembers");
                });

            modelBuilder.Entity("Mahjong.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Mahjong.Api.Models.Game", b =>
                {
                    b.HasOne("Mahjong.Api.Models.PlayGroup", "PlayGroup")
                        .WithMany("Games")
                        .HasForeignKey("PlayGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mahjong.Api.Models.Player", "WinnerPlayer")
                        .WithMany()
                        .HasForeignKey("WinnerPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlayGroup");

                    b.Navigation("WinnerPlayer");
                });

            modelBuilder.Entity("Mahjong.Api.Models.GameParticipation", b =>
                {
                    b.HasOne("Mahjong.Api.Models.Game", "Game")
                        .WithMany("Participations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mahjong.Api.Models.Player", "Player")
                        .WithMany("Participations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Mahjong.Api.Models.PlayGroupMember", b =>
                {
                    b.HasOne("Mahjong.Api.Models.PlayGroup", "PlayGroup")
                        .WithMany("Members")
                        .HasForeignKey("PlayGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mahjong.Api.Models.Player", "Player")
                        .WithMany("PlayGroupMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayGroup");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Mahjong.Api.Models.Game", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Mahjong.Api.Models.PlayGroup", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Mahjong.Api.Models.Player", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("PlayGroupMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
