name: Run Backend Unit Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up containers
        uses: docker/setup-buildx-action@v3
      - name: Build backend container
        run: docker compose build backend
      - name: Run backend tests
        run: make test